version: '3'

services:
  postgresjob:
    image: 'postgres'
    container_name: postgresjob
    environment:
      POSTGRES_PASSWORD: '123456'
      POSTGRES_USER: 'docker'
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - appNetwork

  server:
    build: .
    ports:
      - '6000:6000'
    depends_on:
      - postgresjob
    networks:
      - appNetwork
    links:
      - postgresjob

networks:
  appNetwork:
    driver: bridge

volumes:
  data:
